package com.mystore.Objects;

public enum Tags {
    ASEO_HOGAR, BEBIDAS, CARNES_FRIAS_Y_CONGELADOS, CIGARRILLOS, CUIDADO_BEBE, CUIDADO_PERSONAL, CUIDADO_ROPA, DESPENSA, DROGUERIA, DULCES_Y_POSTRES, ELECTRODOMESTICOS, HELADOS, HOGAR_Y_DECORACION, ILUMINACION_Y_ELECTRICOS, LACTEOS_HUEVOS_Y_REFRIGERADOS, LIMPIEZA_COCINA, MASCOTAS, PANADERIA_Y_PASTELERIA,PASABOCAS, VINOS_Y_LICORES
}

