package com.mystore.Objects;

import com.mystore.Objects.tags;

public enum Tipe {
    Ambientadores(tags.ASEO_HOGAR),
    Blanqueadores(tags.ASEO_HOGAR),
    Cera(tags.ASEO_HOGAR),
    Desinfectantes(tags.ASEO_HOGAR),
    Insecticidas(tags.ASEO_HOGAR),
    Limpieza_de_Superficies(tags.ASEO_HOGAR),
    Agua(tags.BEBIDAS),
    Energizantes(tags.BEBIDAS),
    Gaseosas(tags.BEBIDAS),
    Hidratantes(tags.BEBIDAS),
    Jugos_Refrescos_y_Maltas(tags.BEBIDAS),
    Te_Liquido(tags.BEBIDAS),
    Congelados(tags.CARNES_FRIAS_Y_CONGELADOS),
    Empanadas(tags.CARNES_FRIAS_Y_CONGELADOS),
    Papas_Yucas_y_Patacones(tags.CARNES_FRIAS_Y_CONGELADOS),
    Cigarrillos(tags.CIGARRILLOS),
    Alimentacion(tags.CUIDADO_BEBE),
    Pañales(tags.CUIDADO_BEBE),
    Pañitos(tags.CUIDADO_BEBE),
    Afeitado(tags.CUIDADO_PERSONAL),
    Cremas_Corporales(tags.CUIDADO_PERSONAL),
    Cuidado_Oral(tags.CUIDADO_PERSONAL),
    Desodorantes(tags.CUIDADO_PERSONAL),
    Gel(tags.CUIDADO_PERSONAL),
    Jabones_de_Tocador(tags.CUIDADO_PERSONAL),
    Papel_Higienico(tags.CUIDADO_PERSONAL),
    Proteccion_Femenina(tags.CUIDADO_PERSONAL),
    Shampoo(tags.CUIDADO_PERSONAL),
    Detergentes(tags.CUIDADO_ROPA),
    Jabones_en_Barra(tags.CUIDADO_ROPA),
    Aceites(tags.DESPENSA),
    Arroz_y_Granos(tags.DESPENSA),
    Avenas(tags.DESPENSA),
    Azucar_y_Panelas(tags.DESPENSA),
    Bases_Cremas_y_Sopas(tags.DESPENSA),
    Bebidas_Achocolatadas_en_Polvo(tags.DESPENSA),
    Cafe(tags.DESPENSA),
    Cereales(tags.DESPENSA),
    Choolates_de_Mesa(tags.DESPENSA),
    Condimentos_caldos_y_sal(tags.DESPENSA),
    Enlatados_y_Conservas(tags.DESPENSA),
    Harinas_y_Mezclas(tags.DESPENSA),
    Pastas(tags.DESPENSA),
    Salsas_y_Vinagres(tags.DESPENSA),
    Te_infusiones_e_instantaneos(tags.DESPENSA),
    Salud_y_Bienestar(tags.DROGUERIA),
    Arequipe(tags.DULCES_Y_POSTRES),
    Chocolateria(tags.DULCES_Y_POSTRES),
    Confites_y_dulces(tags.DULCES_Y_POSTRES),
    Crema_de_Leche_y_Leche_Condensada(tags.DULCES_Y_POSTRES),
    Dulces_Tipicos(tags.DULCES_Y_POSTRES),
    Gelatinas_flanes_y_pudines(tags.DULCES_Y_POSTRES),
    Leche_Condensada(tags.DULCES_Y_POSTRES),
    Reposteria(tags.DULCES_Y_POSTRES),
    Electrodomesticos(tags.ELECTRODOMESTICOS),
    Helados(tags.HELADOS),
    Desechables(tags.HOGAR_Y_DECORACION),
    Bombillos(tags.ILUMINACION_Y_ELECTRICOS),
    Pilas(tags.ILUMINACION_Y_ELECTRICOS),
    Alpinette(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Alpinito(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Arepas(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Avena(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Carnes_frias_y_Embutidos(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Gelatina(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Huevos(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Kumis(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Leche(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Leches(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Leches_en_Polvo(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Mantequilla(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Margarinas(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Quesos(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Yogurt(tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Bolsas_de_Basura(tags.LIMPIEZA_COCINA),
    Esponjas_y_Fibras(tags.LIMPIEZA_COCINA),
    Lavaloza(tags.LIMPIEZA_COCINA),
    Servilletas(tags.LIMPIEZA_COCINA),
    Traperos_Escobas(tags.LIMPIEZA_COCINA),
    Aves(tags.MASCOTAS),
    Gatos(tags.MASCOTAS),
    Hamsters(tags.MASCOTAS),
    Perro(tags.MASCOTAS),
    Pez(tags.MASCOTAS),
    Panaderia_Empacada(tags.PANADERIA_Y_PASTELERIA),
    Galletas_Dulces(tags.PASABOCAS),
    Galletas_Saladas(tags.PASABOCAS),
    Galletas_Saludables(tags.PASABOCAS),
    Papas_Fritas_y_Paquetes(tags.PASABOCAS),
    Aguardiente(tags.VINOS_Y_LICORES),
    Brandy(tags.VINOS_Y_LICORES),
    Cerveza(tags.VINOS_Y_LICORES),
    Ginebra(tags.VINOS_Y_LICORES),
    Licor(tags.VINOS_Y_LICORES),
    Ron(tags.VINOS_Y_LICORES),
    Vinos(tags.VINOS_Y_LICORES),
    Vodka(tags.VINOS_Y_LICORES),
    Whisky(tags.VINOS_Y_LICORES),

    public tags Tags;

    Tipe(tags Tags){
        this.Tags = Tags;
    }

    public tags getTag() {
        return Tags;
    }

}
