package com.mystore.Objects;

public enum Type {
    Ambientadores(Tags.ASEO_HOGAR),
    Blanqueadores(Tags.ASEO_HOGAR),
    Cera(Tags.ASEO_HOGAR),
    Desinfectantes(Tags.ASEO_HOGAR),
    Insecticidas(Tags.ASEO_HOGAR),
    Limpieza_de_Superficies(Tags.ASEO_HOGAR),
    Agua(Tags.BEBIDAS),
    Energizantes(Tags.BEBIDAS),
    Gaseosas(Tags.BEBIDAS),
    Hidratantes(Tags.BEBIDAS),
    Jugos_Refrescos_y_Maltas(Tags.BEBIDAS),
    Te_Liquido(Tags.BEBIDAS),
    Congelados(Tags.CARNES_FRIAS_Y_CONGELADOS),
    Empanadas(Tags.CARNES_FRIAS_Y_CONGELADOS),
    Papas_Yucas_y_Patacones(Tags.CARNES_FRIAS_Y_CONGELADOS),
    Cigarrillos(Tags.CIGARRILLOS),
    Alimentacion(Tags.CUIDADO_BEBE),
    Pañales(Tags.CUIDADO_BEBE),
    Pañitos(Tags.CUIDADO_BEBE),
    Afeitado(Tags.CUIDADO_PERSONAL),
    Cremas_Corporales(Tags.CUIDADO_PERSONAL),
    Cuidado_Oral(Tags.CUIDADO_PERSONAL),
    Desodorantes(Tags.CUIDADO_PERSONAL),
    Gel(Tags.CUIDADO_PERSONAL),
    Jabones_de_Tocador(Tags.CUIDADO_PERSONAL),
    Papel_Higienico(Tags.CUIDADO_PERSONAL),
    Proteccion_Femenina(Tags.CUIDADO_PERSONAL),
    Shampoo(Tags.CUIDADO_PERSONAL),
    Detergentes(Tags.CUIDADO_ROPA),
    Jabones_en_Barra(Tags.CUIDADO_ROPA),
    Aceites(Tags.DESPENSA),
    Arroz_y_Granos(Tags.DESPENSA),
    Avenas(Tags.DESPENSA),
    Azucar_y_Panelas(Tags.DESPENSA),
    Bases_Cremas_y_Sopas(Tags.DESPENSA),
    Bebidas_Achocolatadas_en_Polvo(Tags.DESPENSA),
    Cafe(Tags.DESPENSA),
    Cereales(Tags.DESPENSA),
    Choolates_de_Mesa(Tags.DESPENSA),
    Condimentos_caldos_y_sal(Tags.DESPENSA),
    Enlatados_y_Conservas(Tags.DESPENSA),
    Harinas_y_Mezclas(Tags.DESPENSA),
    Pastas(Tags.DESPENSA),
    Salsas_y_Vinagres(Tags.DESPENSA),
    Te_infusiones_e_instantaneos(Tags.DESPENSA),
    Salud_y_Bienestar(Tags.DROGUERIA),
    Arequipe(Tags.DULCES_Y_POSTRES),
    Chocolateria(Tags.DULCES_Y_POSTRES),
    Confites_y_dulces(Tags.DULCES_Y_POSTRES),
    Crema_de_Leche_y_Leche_Condensada(Tags.DULCES_Y_POSTRES),
    Dulces_Tipicos(Tags.DULCES_Y_POSTRES),
    Gelatinas_flanes_y_pudines(Tags.DULCES_Y_POSTRES),
    Leche_Condensada(Tags.DULCES_Y_POSTRES),
    Reposteria(Tags.DULCES_Y_POSTRES),
    Electrodomesticos(Tags.ELECTRODOMESTICOS),
    Helados(Tags.HELADOS),
    Desechables(Tags.HOGAR_Y_DECORACION),
    Bombillos(Tags.ILUMINACION_Y_ELECTRICOS),
    Pilas(Tags.ILUMINACION_Y_ELECTRICOS),
    Alpinette(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Alpinito(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Arepas(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Avena(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Carnes_frias_y_Embutidos(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Gelatina(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Huevos(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Kumis(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Leche(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Leches(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Leches_en_Polvo(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Mantequilla(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Margarinas(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Quesos(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Yogurt(Tags.LACTEOS_HUEVOS_Y_REFRIGERADOS),
    Bolsas_de_Basura(Tags.LIMPIEZA_COCINA),
    Esponjas_y_Fibras(Tags.LIMPIEZA_COCINA),
    Lavaloza(Tags.LIMPIEZA_COCINA),
    Servilletas(Tags.LIMPIEZA_COCINA),
    Traperos_Escobas(Tags.LIMPIEZA_COCINA),
    Aves(Tags.MASCOTAS),
    Gatos(Tags.MASCOTAS),
    Hamsters(Tags.MASCOTAS),
    Perro(Tags.MASCOTAS),
    Pez(Tags.MASCOTAS),
    Panaderia_Empacada(Tags.PANADERIA_Y_PASTELERIA),
    Galletas_Dulces(Tags.PASABOCAS),
    Galletas_Saladas(Tags.PASABOCAS),
    Galletas_Saludables(Tags.PASABOCAS),
    Papas_Fritas_y_Paquetes(Tags.PASABOCAS),
    Aguardiente(Tags.VINOS_Y_LICORES),
    Brandy(Tags.VINOS_Y_LICORES),
    Cerveza(Tags.VINOS_Y_LICORES),
    Ginebra(Tags.VINOS_Y_LICORES),
    Licor(Tags.VINOS_Y_LICORES),
    Ron(Tags.VINOS_Y_LICORES),
    Vinos(Tags.VINOS_Y_LICORES),
    Vodka(Tags.VINOS_Y_LICORES),
    Whisky(Tags.VINOS_Y_LICORES);

    public final Tags tags;

    Type(Tags tags){
        this.tags = tags;
    }

    public Tags getTag() {
        return tags;
    }

}
